version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.49.2:31112
functions:
  app:
    lang: python3
    version: 3.9
    handler: ./app
    image: app:latest
    build_args:
      ADDITIONAL_PACKAGE: "ffmpeg gcc cmake"

